### PR TITLE
Changes proposed for hardware.cpp pinMode and WEMOS_D1_R32.json

### PR DESCRIPTION
**Pull request by KirikauKiwi**
When looking in to the invalid pin problem I was having, I looked into manual pinMode configurations and the board default pin configurations and a few other things.

Serial.begin, SPI.begin and Wire.begin will usually use the default pins for a particular board if not otherwise defined, typical they would defined like this.
```
Wire.begin(21, 22);  // Automatically configures pins 21 and 22 for I2C
```
It appears it is not typical to manually configure Serial, SPI and Wire.pins as it is usually done automatically with the function call which will set the appropriate pinMode.

The changes I have suggested are based on this information and setting the pinMode manually, along with a couple of changes from pinModes that are currently set as an INPUT pin when they are usually OUTPUT pins such as UART TX is considered an OUPUT and UART RX an INPUT, MOSI is consider an OUTPUT and SDA & SCL should be set as INPUT_PULLUP (note I just checked the DIYFB schematic and see you have pull-up resistors on the board so you can ignore the INPUT_PULLUP change I suggested), it maybe good to add this in the Wiki for those not using the DIYFB shield, such as my self currently.

I noticed that the current WEMO pins.json appears to have the UART2 TX pin assigned to what is labeled as SERIAL2_RX_PIN from the diagrams I have referenced for the D1 R32 Board Pinouts.

I am passing this as as information only that I have found when trying to solve my issue, your DIYFB project is helping me learn a great deal about C++ and the MCU setup etc. I hope it is of use if it is something you don't know about, otherwise please ignore. I am a fan of honest communication and knowledge sharing, learning and such.

### CODE REVIEW

**Comment by DeeEmm** [comment]
Good catch on the serial 2 pin assignment. Thanks 😄 👍 

I think that it is better to add the requirement for pull-ups for I2C to the WIKI as they are part of the I2C standard and so (in my mind) should be in hardware. 

I will concede that The [shield design overview](https://github.com/DeeEmm/DIY-Flow-Bench/wiki/shield-overview) page is very basic and does not include specific requirements for things like I2C pull-ups as well as other arguably 'critical' details. 

For the most part on other projects that I'm involved with, the schematics are generally enough for anyone wanting to make their own shield without having to explain component choices, as it can simply be followed pro-rote. However this particular page is due for a re-write as part of the pins file changes, so I will add in those details and any other pertinent details that I can think of. I will also have a think about how to expand on the way that the data is presented. Would be great to have something like the interactive BOM for the schematic so that comments could be added that relate to functionality etc...

https://htmlpreview.github.io/?https://github.com/DeeEmm/DIY-Flow-Bench/blob/master/docs/iBom-DIY-FLOW-BENCH-V2-3.html

Your comments are actually fairly timely as it made me realise that we have not added the WIKI to the RC9 tasks. So here it is - #238

I'm not so sure about the change to MOSI, at least not for the WEMOS D1. I say this as when I tested the SD card functionality on the PCB commissioning, it worked as expected. This leads me to think that it is currently correct.

D1 R32

**Comment by DeeEmm** [comment]
Further thoughts on I2C pull-ups in hardware...

There are also pull-ups required on the 5v side of the logic level converter, so IMHO would be odd to have the 3.3v side internal and the 5v side external

**Review by DeeEmm — APPROVED** [review]
With reference to the discussion in the main thread. ~I suspect that the MISO is okay as-is, but this is only based on the fact that the SD card code that I tested is working~

It seems that after looking in the test code, it defaults to the correct I/O, which explains why it works. TBH I've not actually looked at the SD card stuff in depth, only enough to create a quick unit test

**Comment by KirikauKiwi** [comment]
> With reference to the discussion in the main thread. ~I suspect that the MISO is okay as-is, but this is only based on the fact that the SD card code that I tested is working~
> 
> It seems that after looking in the test code, it defaults to the correct I/O, which explains why it works. TBH I've not actually looked at the SD card stuff in depth, only enough to create a quick unit test

Yes I think you are correct that the SPI.begin will use and correctly set the default SPI pinMode for the board and will work how it should, so this is unlikely to effect the DIYFB shield, so more of a thing for custom pin configs on other boards.

What I understood from the reading I did, since the pinModes are being set manually it is best to set the correct pinModes as it removes the potential for any flakiness that may arise if the pinMode wasn't set manually, but the GPIO had been set manually.

**Pull request merged**
